language: node_js
node_js:
  - "10"
  - "11"
  - "12"
before_install:
  - "npm install -g npm@latest"
install:
  - npm install eslint
  - npm install eslint-plugin-import
  - npm install eslint-config-airbnb-base
script:
  - npm run lint
cache:
  directories:
    - node_modules
